# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17B3DyOQu1KJcnNOoJcH-se0oBd2Nvcz4
"""

!pip install groq tavily-python

"""Import"""

import os
from groq import Groq
from tavily import TavilyClient

"""Replace the string inside the double quotes with your actual key"""

os.environ["GROQ_API_KEY"] = "ENTER YOUR GROQ API KEY HERE"
os.environ["TAVILY_API_KEY"] = "ENTER YOUR TAVILY API KEY HERE"

groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])
tavily_client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])
MODELS = ["llama-3.1-8b-instant", "llama3-8b-8192", "mixtral-8x7b-32768"]

def call_llm(system_prompt, user_input):
    for model in MODELS:
        try:
            completion = groq_client.chat.completions.create(
                model=model,
                messages=[{"role": "system", "content": system_prompt}, {"role": "user", "content": user_input}],
                temperature=0.5,
            )
            return completion.choices[0].message.content
        except Exception:
            continue
    return "Error: All models failed."

"""Database Tool Functions"""

def get_exercise_db_data(user_limitation):
    query = f"ExerciseDB database: safe workout exercises for {user_limitation}"
    return tavily_client.search(query=query, search_depth="advanced")

def get_usda_nutrition_data(diet_type):
    query = f"USDA FoodData Central: high protein {diet_type} foods for muscle gain"
    return tavily_client.search(query=query, search_depth="advanced")

"""The MAS Orchestrator
=

---


"""

def run_adaptive_health_mas(goal, diet, limitation):
    user_profile = f"Goal: {goal}, Limitation: {limitation}, Diet: {diet}"
    exercise_data = get_exercise_db_data(limitation)
    nutrition_data = get_usda_nutrition_data(diet)

    #Coach
    coach_prompt = "You are an Elite Coach. Use the ExerciseDB data to create a 7-day workout."
    workout = call_llm(coach_prompt, f"Profile: {user_profile}\nData: {exercise_data}")

    #Nutritionist
    nutri_prompt = "You are a Nutritionist. Use the USDA data to create a meal plan."
    diet_plan = call_llm(nutri_prompt, f"Profile: {user_profile}\nData: {nutrition_data}")

    #Medical auditor
    auditor_prompt = "You are a Doctor. Review the plan. If any exercise is dangerous for the user's LIMITATION, you MUST replace it. Provide the FINAL PLAN."
    final_plan = call_llm(auditor_prompt, f"Profile: {user_profile}\nWorkout: {workout}\nDiet: {diet_plan}")
    return final_plan

"""Interactive User Interface"""

u_goal = input("Enter your Goal (e.g., Muscle Gain): ")
u_diet = input("Enter your Diet (e.g., Vegan): ")

while True:
    u_limitation = input("\nEnter your Limitation (e.g., None or Severe Shoulder Injury) or type 'exit' to stop: ")

    if u_limitation.lower() == 'exit':
        break

    final_result = run_adaptive_health_mas(u_goal, u_diet, u_limitation)
    print(final_result)

