# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L96a1KVLFTyVnJsIGlsStV_pAEkZ_xDE
"""

# =================================================================
# STEP 1: INSTALLATIONS & SETUP
# =================================================================
!pip install groq tavily-python

import os
from groq import Groq
from tavily import TavilyClient

# REPLACE THESE WITH YOUR ACTUAL KEYS
os.environ["GROQ_API_KEY"] = "ENTER YOUR GROQ API KEY HERE"
os.environ["TAVILY_API_KEY"] = "ENTER YOUR TAVILY API KEY HERE"

groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])
tavily_client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])

MODELS = ["llama-3.1-8b-instant", "llama3-8b-8192", "mixtral-8x7b-32768"]

def call_llm(system_prompt, user_input):
    for model in MODELS:
        try:
            completion = groq_client.chat.completions.create(
                model=model,
                messages=[{"role": "system", "content": system_prompt}, {"role": "user", "content": user_input}],
                temperature=0.5,
            )
            return completion.choices[0].message.content
        except Exception:
            continue
    return "Error: All models failed."

# =================================================================
# STEP 2: DATABASE TOOL FUNCTIONS
# =================================================================

def get_exercise_db_data(user_limitation):
    print("🛠️ Tool: Accessing ExerciseDB... Searching for safe movements...")
    query = f"ExerciseDB database: safe workout exercises for {user_limitation}"
    return tavily_client.search(query=query, search_depth="advanced")

def get_usda_nutrition_data(diet_type):
    print("🛠️ Tool: Accessing USDA FoodData Central... Fetching nutrient profiles...")
    query = f"USDA FoodData Central: high protein {diet_type} foods for muscle gain"
    return tavily_client.search(query=query, search_depth="advanced")

# =================================================================
# STEP 3: THE MAS ORCHESTRATOR
# =================================================================

def run_adaptive_health_mas(goal, diet, limitation):
    user_profile = f"Goal: {goal}, Limitation: {limitation}, Diet: {diet}"
    print(f"\n🚀 Processing Plan for: {user_profile}\n")

    # 1. Database Tool Calls
    exercise_data = get_exercise_db_data(limitation)
    nutrition_data = get_usda_nutrition_data(diet)

    # 2. Coach Agent
    print("🏋️ Coach is designing workout...")
    coach_prompt = "You are an Elite Coach. Use the ExerciseDB data to create a 7-day workout."
    workout = call_llm(coach_prompt, f"Profile: {user_profile}\nData: {exercise_data}")

    # 3. Nutritionist Agent
    print("🥗 Nutritionist is designing diet...")
    nutri_prompt = "You are a Nutritionist. Use the USDA data to create a meal plan."
    diet_plan = call_llm(nutri_prompt, f"Profile: {user_profile}\nData: {nutrition_data}")

    # 4. Medical Auditor (THE DYNAMIC PART)
    print("🩺 Medical Auditor is checking for safety...")
    auditor_prompt = "You are a Doctor. Review the plan. If any exercise is dangerous for the user's LIMITATION, you MUST replace it. Provide the FINAL PLAN."
    final_plan = call_llm(auditor_prompt, f"Profile: {user_profile}\nWorkout: {workout}\nDiet: {diet_plan}")

    return final_plan

# =================================================================
# STEP 4: INTERACTIVE USER INTERFACE (For the Video)
# =================================================================

print("--- Welcome to the Adaptive Fitness MAS ---")
# Ask for these ONLY ONCE
u_goal = input("Enter your Goal (e.g., Muscle Gain): ")
u_diet = input("Enter your Diet (e.g., Vegan): ")

while True:
    # Ask for the limitation EVERY TIME to show the dynamic change
    u_limitation = input("\nEnter your Limitation (e.g., None or Severe Shoulder Injury) or type 'exit' to stop: ")

    if u_limitation.lower() == 'exit':
        print("Exiting system. Goodbye!")
        break

    final_result = run_adaptive_health_mas(u_goal, u_diet, u_limitation)

    print("\n\n================ FINAL MEDICALLY APPROVED PLAN =================\n")
    print(final_result)
    print("\n===============================================================\n")

