# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L96a1KVLFTyVnJsIGlsStV_pAEkZ_xDE
"""

# =================================================================
# STEP 1: INSTALLATIONS
# =================================================================
!pip install groq tavily-python

import os
from groq import Groq
from tavily import TavilyClient
# REPLACE THESE WITH YOUR ACTUAL KEYS
os.environ["GROQ_API_KEY"] = "PASTE_YOUR_GROQ_KEY_HERE"
os.environ["TAVILY_API_KEY"] = "PASTE_YOUR_TAVILY_KEY_HERE"

groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])
tavily_client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])

# Fail-safe model list (if one is decommissioned, it tries the next)
MODELS = ["llama-3.1-8b-instant", "llama3-8b-8192", "mixtral-8x7b-32768"]

# =================================================================
# STEP 2: DATABASE TOOL FUNCTIONS (Meeting the Requirements)
# =================================================================

def get_exercise_db_data(user_limitation):
    """TOOL: Fetches exercise data from ExerciseDB via Tavily Research"""
    print("🛠️ Tool: Accessing ExerciseDB... Searching for safe movements...")
    query = f"ExerciseDB database: safe workout exercises for {user_limitation}"
    return tavily_client.search(query=query, search_depth="advanced")

def get_usda_nutrition_data(diet_type):
    """TOOL: Fetches nutritional data from USDA FoodData Central via Tavily Research"""
    print("🛠️ Tool: Accessing USDA FoodData Central... Fetching nutrient profiles...")
    query = f"USDA FoodData Central: high protein {diet_type} foods for muscle gain"
    return tavily_client.search(query=query, search_depth="advanced")

def call_llm(system_prompt, user_input):
    """Robust LLM caller with fail-safe model switching"""
    for model in MODELS:
        try:
            completion = groq_client.chat.completions.create(
                model=model,
                messages=[{"role": "system", "content": system_prompt}, {"role": "user", "content": user_input}],
                temperature=0.5,
            )
            return completion.choices[0].message.content
        except Exception:
            continue
    return "Error: All models failed."

# =================================================================
# STEP 3: THE MULTI-AGENT SYSTEM (MAS)
# =================================================================

def run_adaptive_health_mas(user_profile):
    print(f"\n🚀 Initializing MAS for: {user_profile}\n")

    # 1. Gather data using the required databases
    exercise_data = get_exercise_db_data(user_profile)
    nutrition_data = get_usda_nutrition_data("Vegan") # Assuming Vegan based on prompt

    # --- AGENT 1: THE FITNESS COACH ---
    print("🏋️ Agent 1 (Coach): Designing workout using ExerciseDB data...")
    coach_prompt = "You are an Elite Coach. Use the provided ExerciseDB research to create a 7-day workout. Be specific."
    workout = call_llm(coach_prompt, f"User: {user_profile}\nData: {exercise_data}")

    # --- AGENT 2: THE NUTRITIONIST ---
    print("🥗 Agent 2 (Nutritionist): Designing diet using USDA data...")
    nutri_prompt = "You are a Nutritionist. Use the USDA nutrition data to create a meal plan for muscle gain."
    diet = call_llm(nutri_prompt, f"User: {user_profile}\nData: {nutrition_data}")

    # --- AGENT 3: THE MEDICAL AUDITOR (DYNAMIC ADJUSTMENT) ---
    print("🩺 Agent 3 (Medical Auditor): Performing safety check & dynamic adjustment...")
    auditor_prompt = "You are a Doctor. Review the plan. If any exercise is dangerous for the user's LIMITATIONS, you MUST replace it. Provide the FINAL APPROVED PLAN."
    final_plan = call_llm(auditor_prompt, f"User: {user_profile}\nWorkout: {workout}\nDiet: {diet}")

    return final_plan

# =================================================================
# STEP 4: EXECUTION (Change 'user_info' for your video!)
# =================================================================

# Scenario: Change to "Limitation: None" for the first half of your video
user_info = input("Please enter your profile (Goal, Limitation, Diet): ")
result = run_adaptive_health_mas(user_info)

print("\n\n================ FINAL MEDICALLY APPROVED PLAN =================\n")
print(result)

